name: run unit test of feature branches

on:
  push:
    branches:
      'feature/*'


    jobs:
      run-unit-tests:
        runs-on: windows

        steps:
          - name: Checkout
            uses: actions/checkout@v6.0.1

          - name: run
            run: mvn test